// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.bigdata.netty.proto;

/**
 * Protobuf type {@code com.bigdata.proto.MyResponse}
 */
public  final class MyResponse extends
    com.google.protobuf.GeneratedMessageLite<
        MyResponse, MyResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:com.bigdata.proto.MyResponse)
        MyResponseOrBuilder {
  private MyResponse() {
    realname_ = "";
  }
  public static final int REALNAME_FIELD_NUMBER = 2;
  private String realname_;
  /**
   * <code>string realname = 2;</code>
   * @return The realname.
   */
  @Override
  public String getRealname() {
    return realname_;
  }
  /**
   * <code>string realname = 2;</code>
   * @return The bytes for realname.
   */
  @Override
  public com.google.protobuf.ByteString
      getRealnameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(realname_);
  }
  /**
   * <code>string realname = 2;</code>
   * @param value The realname to set.
   */
  private void setRealname(
      String value) {
    Class<?> valueClass = value.getClass();
  
    realname_ = value;
  }
  /**
   * <code>string realname = 2;</code>
   */
  private void clearRealname() {
    
    realname_ = getDefaultInstance().getRealname();
  }
  /**
   * <code>string realname = 2;</code>
   * @param value The bytes for realname to set.
   */
  private void setRealnameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    realname_ = value.toStringUtf8();
    
  }

  public static MyResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static MyResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static MyResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static MyResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static MyResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static MyResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static MyResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static MyResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static MyResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static MyResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static MyResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static MyResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(MyResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.bigdata.proto.MyResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              MyResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bigdata.proto.MyResponse)
          MyResponseOrBuilder {
    // Construct using com.bigdata.proto.MyResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string realname = 2;</code>
     * @return The realname.
     */
    @Override
    public String getRealname() {
      return instance.getRealname();
    }
    /**
     * <code>string realname = 2;</code>
     * @return The bytes for realname.
     */
    @Override
    public com.google.protobuf.ByteString
        getRealnameBytes() {
      return instance.getRealnameBytes();
    }
    /**
     * <code>string realname = 2;</code>
     * @param value The realname to set.
     * @return This builder for chaining.
     */
    public Builder setRealname(
        String value) {
      copyOnWrite();
      instance.setRealname(value);
      return this;
    }
    /**
     * <code>string realname = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRealname() {
      copyOnWrite();
      instance.clearRealname();
      return this;
    }
    /**
     * <code>string realname = 2;</code>
     * @param value The bytes for realname to set.
     * @return This builder for chaining.
     */
    public Builder setRealnameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRealnameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.bigdata.proto.MyResponse)
  }
  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new MyResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          Object[] objects = new Object[] {
            "realname_",
          };
          String info =
              "\u0000\u0001\u0000\u0000\u0002\u0002\u0001\u0000\u0000\u0000\u0002\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<MyResponse> parser = PARSER;
        if (parser == null) {
          synchronized (MyResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<MyResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.bigdata.proto.MyResponse)
  private static final MyResponse DEFAULT_INSTANCE;
  static {
    MyResponse defaultInstance = new MyResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      MyResponse.class, defaultInstance);
  }

  public static MyResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<MyResponse> PARSER;

  public static com.google.protobuf.Parser<MyResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

