// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.bigdata.netty.proto;

/**
 * Protobuf type {@code com.bigdata.proto.StreamResponse}
 */
public  final class StreamResponse extends
    com.google.protobuf.GeneratedMessageLite<
        StreamResponse, StreamResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:com.bigdata.proto.StreamResponse)
        StreamResponseOrBuilder {
  private StreamResponse() {
    responseInfo_ = "";
  }
  public static final int RESPONSE_INFO_FIELD_NUMBER = 1;
  private String responseInfo_;
  /**
   * <code>string response_info = 1;</code>
   * @return The responseInfo.
   */
  @Override
  public String getResponseInfo() {
    return responseInfo_;
  }
  /**
   * <code>string response_info = 1;</code>
   * @return The bytes for responseInfo.
   */
  @Override
  public com.google.protobuf.ByteString
      getResponseInfoBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(responseInfo_);
  }
  /**
   * <code>string response_info = 1;</code>
   * @param value The responseInfo to set.
   */
  private void setResponseInfo(
      String value) {
    Class<?> valueClass = value.getClass();
  
    responseInfo_ = value;
  }
  /**
   * <code>string response_info = 1;</code>
   */
  private void clearResponseInfo() {
    
    responseInfo_ = getDefaultInstance().getResponseInfo();
  }
  /**
   * <code>string response_info = 1;</code>
   * @param value The bytes for responseInfo to set.
   */
  private void setResponseInfoBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    responseInfo_ = value.toStringUtf8();
    
  }

  public static StreamResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static StreamResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static StreamResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static StreamResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static StreamResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static StreamResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static StreamResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static StreamResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static StreamResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static StreamResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static StreamResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static StreamResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(StreamResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.bigdata.proto.StreamResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              StreamResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bigdata.proto.StreamResponse)
          StreamResponseOrBuilder {
    // Construct using com.bigdata.proto.StreamResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string response_info = 1;</code>
     * @return The responseInfo.
     */
    @Override
    public String getResponseInfo() {
      return instance.getResponseInfo();
    }
    /**
     * <code>string response_info = 1;</code>
     * @return The bytes for responseInfo.
     */
    @Override
    public com.google.protobuf.ByteString
        getResponseInfoBytes() {
      return instance.getResponseInfoBytes();
    }
    /**
     * <code>string response_info = 1;</code>
     * @param value The responseInfo to set.
     * @return This builder for chaining.
     */
    public Builder setResponseInfo(
        String value) {
      copyOnWrite();
      instance.setResponseInfo(value);
      return this;
    }
    /**
     * <code>string response_info = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseInfo() {
      copyOnWrite();
      instance.clearResponseInfo();
      return this;
    }
    /**
     * <code>string response_info = 1;</code>
     * @param value The bytes for responseInfo to set.
     * @return This builder for chaining.
     */
    public Builder setResponseInfoBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setResponseInfoBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.bigdata.proto.StreamResponse)
  }
  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new StreamResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          Object[] objects = new Object[] {
            "responseInfo_",
          };
          String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<StreamResponse> parser = PARSER;
        if (parser == null) {
          synchronized (StreamResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<StreamResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.bigdata.proto.StreamResponse)
  private static final StreamResponse DEFAULT_INSTANCE;
  static {
    StreamResponse defaultInstance = new StreamResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      StreamResponse.class, defaultInstance);
  }

  public static StreamResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<StreamResponse> PARSER;

  public static com.google.protobuf.Parser<StreamResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

