// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.bigdata.netty.proto;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bigdata.proto.StreamResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string response_info = 1;</code>
   * @return The responseInfo.
   */
  String getResponseInfo();
  /**
   * <code>string response_info = 1;</code>
   * @return The bytes for responseInfo.
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
