// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.bigdata.netty.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
