// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.bigdata.netty.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bigdata.proto.StudentResponseList)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentResponseList();
  /**
   * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
   */
  StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
}
