// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.bigdata.netty.proto;

/**
 * Protobuf type {@code com.bigdata.proto.StudentResponseList}
 */
public  final class StudentResponseList extends
    com.google.protobuf.GeneratedMessageLite<
        StudentResponseList, StudentResponseList.Builder> implements
    // @@protoc_insertion_point(message_implements:com.bigdata.proto.StudentResponseList)
        StudentResponseListOrBuilder {
  private StudentResponseList() {
    studentResponse_ = emptyProtobufList();
  }
  public static final int STUDENTRESPONSE_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<StudentResponse> studentResponse_;
  /**
   * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
   */
  @Override
  public java.util.List<StudentResponse> getStudentResponseList() {
    return studentResponse_;
  }
  /**
   * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
   */
  public java.util.List<? extends StudentResponseOrBuilder>
      getStudentResponseOrBuilderList() {
    return studentResponse_;
  }
  /**
   * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
   */
  @Override
  public int getStudentResponseCount() {
    return studentResponse_.size();
  }
  /**
   * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
   */
  @Override
  public StudentResponse getStudentResponse(int index) {
    return studentResponse_.get(index);
  }
  /**
   * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
   */
  public StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index) {
    return studentResponse_.get(index);
  }
  private void ensureStudentResponseIsMutable() {
    com.google.protobuf.Internal.ProtobufList<StudentResponse> tmp = studentResponse_;
    if (!tmp.isModifiable()) {
      studentResponse_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
   */
  private void setStudentResponse(
      int index, StudentResponse value) {
    value.getClass();
  ensureStudentResponseIsMutable();
    studentResponse_.set(index, value);
  }
  /**
   * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
   */
  private void addStudentResponse(StudentResponse value) {
    value.getClass();
  ensureStudentResponseIsMutable();
    studentResponse_.add(value);
  }
  /**
   * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
   */
  private void addStudentResponse(
      int index, StudentResponse value) {
    value.getClass();
  ensureStudentResponseIsMutable();
    studentResponse_.add(index, value);
  }
  /**
   * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
   */
  private void addAllStudentResponse(
      Iterable<? extends StudentResponse> values) {
    ensureStudentResponseIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, studentResponse_);
  }
  /**
   * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
   */
  private void clearStudentResponse() {
    studentResponse_ = emptyProtobufList();
  }
  /**
   * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
   */
  private void removeStudentResponse(int index) {
    ensureStudentResponseIsMutable();
    studentResponse_.remove(index);
  }

  public static StudentResponseList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static StudentResponseList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static StudentResponseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static StudentResponseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static StudentResponseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static StudentResponseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static StudentResponseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static StudentResponseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static StudentResponseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static StudentResponseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static StudentResponseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static StudentResponseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(StudentResponseList prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.bigdata.proto.StudentResponseList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              StudentResponseList, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bigdata.proto.StudentResponseList)
          StudentResponseListOrBuilder {
    // Construct using com.bigdata.proto.StudentResponseList.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
     */
    @Override
    public java.util.List<StudentResponse> getStudentResponseList() {
      return java.util.Collections.unmodifiableList(
          instance.getStudentResponseList());
    }
    /**
     * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
     */
    @Override
    public int getStudentResponseCount() {
      return instance.getStudentResponseCount();
    }/**
     * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
     */
    @Override
    public StudentResponse getStudentResponse(int index) {
      return instance.getStudentResponse(index);
    }
    /**
     * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
     */
    public Builder setStudentResponse(
        int index, StudentResponse value) {
      copyOnWrite();
      instance.setStudentResponse(index, value);
      return this;
    }
    /**
     * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
     */
    public Builder setStudentResponse(
        int index, StudentResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setStudentResponse(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
     */
    public Builder addStudentResponse(StudentResponse value) {
      copyOnWrite();
      instance.addStudentResponse(value);
      return this;
    }
    /**
     * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
     */
    public Builder addStudentResponse(
        int index, StudentResponse value) {
      copyOnWrite();
      instance.addStudentResponse(index, value);
      return this;
    }
    /**
     * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
     */
    public Builder addStudentResponse(
        StudentResponse.Builder builderForValue) {
      copyOnWrite();
      instance.addStudentResponse(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
     */
    public Builder addStudentResponse(
        int index, StudentResponse.Builder builderForValue) {
      copyOnWrite();
      instance.addStudentResponse(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
     */
    public Builder addAllStudentResponse(
        Iterable<? extends StudentResponse> values) {
      copyOnWrite();
      instance.addAllStudentResponse(values);
      return this;
    }
    /**
     * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
     */
    public Builder clearStudentResponse() {
      copyOnWrite();
      instance.clearStudentResponse();
      return this;
    }
    /**
     * <code>repeated .com.bigdata.proto.StudentResponse studentResponse = 1;</code>
     */
    public Builder removeStudentResponse(int index) {
      copyOnWrite();
      instance.removeStudentResponse(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.bigdata.proto.StudentResponseList)
  }
  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new StudentResponseList();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          Object[] objects = new Object[] {
            "studentResponse_",
            StudentResponse.class,
          };
          String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<StudentResponseList> parser = PARSER;
        if (parser == null) {
          synchronized (StudentResponseList.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<StudentResponseList>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.bigdata.proto.StudentResponseList)
  private static final StudentResponseList DEFAULT_INSTANCE;
  static {
    StudentResponseList defaultInstance = new StudentResponseList();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      StudentResponseList.class, defaultInstance);
  }

  public static StudentResponseList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<StudentResponseList> PARSER;

  public static com.google.protobuf.Parser<StudentResponseList> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

